### PR TITLE
Define Breadcrumb Model

### PR DESCRIPTION
**Pull request by davidw-foxtrax**

### CODE REVIEW

**Comment by WW-CICD** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: pr-CodeBuild-WWTelematicsGPSBreadcrumbService-CodeBuildProject
* Commit ID: 6e270082495500faec605394add892d3b694f481
* Result: FAILED
* [Build Logs](https://fr7kathi76.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=7d4cfac3-d8ba-47fc-9dad-b36bdc3c82a9%2Fbuild.log) (available for 10 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by WW-CICD** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: pr-CodeBuild-WWTelematicsGPSBreadcrumbService-CodeBuildProject
* Commit ID: 7a5f3df800a569665bb6badbf1f700d3f415946c
* Result: FAILED
* [Build Logs](https://fr7kathi76.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=6958dd94-7dfc-46c2-af6f-0734ac9aeadb%2Fbuild.log) (available for 10 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by WW-CICD** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: pr-CodeBuild-WWTelematicsGPSBreadcrumbService-CodeBuildProject
* Commit ID: 54d2cac4200b23980619741a32a228682aaf8de7
* Result: SUCCEEDED
* [Build Logs](https://fr7kathi76.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e9a5495e-902e-4f09-b63e-3431de2d8669%2Fbuild.log) (available for 10 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by davidw-foxtrax** [comment]
Replaced by #4

**Pull request closed without merging**
