### PR TITLE
Optional get params

### PR DESCRIPTION
**Pull request by davidw-foxtrax**
Add support for startTime and endTime, and make pageSize default to infinite (required for backwards compatiblity)

### CODE REVIEW

**Comment by WW-CICD** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: pr-CodeBuild-WWTelematicsGPSBreadcrumbService-CodeBuildProject
* Commit ID: cf475b4a76b63a611ac3687fc949e3652a01311f
* Result: SUCCEEDED
* [Build Logs](https://fr7kathi76.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=94f1eec9-3bdc-4e5b-bb6e-7f7d714ff29a%2Fbuild.log) (available for 10 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by WW-CICD** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: pr-CodeBuild-WWTelematicsGPSBreadcrumbService-CodeBuildProject
* Commit ID: 54a9cf8b67ff7093a83557f9a98d00d4f189c9a2
* Result: FAILED
* [Build Logs](https://fr7kathi76.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c9dba4fd-25f4-4db7-b375-a9820d6cf906%2Fbuild.log) (available for 10 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by davidw-foxtrax** [comment]
This PR now supports device filtering.  This requires calling the device microservice to filter the list.

This led to some changes to the model, so this PR replaces #3  and #2.  It depends on WorkWave/WWTelematics.DeviceService#11

**Comment by WW-CICD** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: pr-CodeBuild-WWTelematicsGPSBreadcrumbService-CodeBuildProject
* Commit ID: 222f58e3296c14e0f56e99564149d38fda9ec9ee
* Result: FAILED
* [Build Logs](https://fr7kathi76.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=1bbec3b1-219c-44de-b9ae-13362ce7cf87%2Fbuild.log) (available for 10 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by WW-CICD** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: pr-CodeBuild-WWTelematicsGPSBreadcrumbService-CodeBuildProject
* Commit ID: faff1d672f20307773bc807678f1e5978e9ee99f
* Result: SUCCEEDED
* [Build Logs](https://fr7kathi76.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=422c3129-9d3d-4294-a4d9-c2ed4106d0c0%2Fbuild.log) (available for 10 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by WW-CICD** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: pr-CodeBuild-WWTelematicsGPSBreadcrumbService-CodeBuildProject
* Commit ID: 464079b1f3f8dd7ec1edb9d6eeb8ecd191b37abc
* Result: SUCCEEDED
* [Build Logs](https://fr7kathi76.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=3acae7b8-f29c-4b93-b1b9-054551005fcd%2Fbuild.log) (available for 10 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by WW-CICD** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: pr-CodeBuild-WWTelematicsGPSBreadcrumbService-CodeBuildProject
* Commit ID: 9f2ef8c9a7e39c29abfe6b4031fe2a2c65483260
* Result: SUCCEEDED
* [Build Logs](https://fr7kathi76.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=67bf1ede-009d-4cb0-a9d4-2a061fbc8808%2Fbuild.log) (available for 10 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
